---
- name: Get brew prefix
  ansible.builtin.command: brew --prefix
  register: brew_prefix
  changed_when: false
  check_mode: false

- name: Set brew prefix fact
  ansible.builtin.set_fact:
    brew_prefix: "{{ brew_prefix.stdout }}"

# vi:ft=ansible
