---
- name: Install Google Cloud SDK
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
  - google-cloud-sdk

- name: Install Google Cloud SDK components
  ansible.builtin.command: gcloud components list --format json
  changed_when: false
  check_mode: false
  register: gcloud_installed_components
  tags: here

- name: Install Google Cloud SDK components
  ansible.builtin.command: gcloud components install {{ item }}
  with_items:
  - alpha
  - beta
  - kubectl
  when: "'Not Installed' in gcloud_installed_components.stdout | from_json | json_query('[?id==`alpha`].state.name')"
  tags: here

- name: Get gcloud path status
  ansible.builtin.stat:
    path: "{{ brew_prefix }}/bin/gcloud"
  register: gcloud_prefix

- name: Set fact with glcoud components bin path
  ansible.builtin.set_fact:
    glcoud_components_bin: "{{ gcloud_prefix.stat.lnk_source | dirname }}"

- name: Link gcloud component
  ansible.builtin.file:
    src: "{{ glcoud_components_bin }}/kubectl"
    dest: "{{ brew_prefix }}/bin/kubectl"
    state: link

- name: Update Google Cloud SDK components
  ansible.builtin.command: gcloud components update
  when: pkg_state == "latest"

# vi:ft=ansible
