---
- name: Enable screensaver password
  community.general.system.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: integer
    value: "1"
    state: present
  notify: Reload OS X Dock

- name: Set screensaver password immediately
  community.general.system.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: "0"
    state: present
  notify: Reload OS X Dock

- name: Configure Default terminal profile
  community.general.system.osx_defaults:
    domain: com.apple.Terminal
    key: Default Window Settings
    type: string
    value: Homebrew
    state: present
  notify: Reload OS X Dock

- name: Configure startup terminal profile
  community.general.system.osx_defaults:
    domain: com.apple.Terminal
    key: Startup Window Settings
    type: string
    value: Homebrew
    state: present
  notify: Reload OS X Dock

- name: Configure Terminal focus to follow mouse
  community.general.system.osx_defaults:
    domain: com.apple.Terminal
    key: FocusFollowsMouse
    type: bool
    value: true
    state: present

# TODO: This is a complex value, how to do this?
# - osx_defaults: domain="com.apple.Terminal" key="shellExitAction" type="integer"  value="0" state="present"

- name: Autohide OS X dock
  community.general.system.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "1"
    state: present
  notify: Reload OS X Dock

- name: Set dock size
  community.general.system.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "38"
    state: present
  notify: Reload OS X Dock

- name: Enable docker magnification
  community.general.system.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: "1"
    state: present
  notify: Reload OS X Dock

- name: Set dock magnification max size
  community.general.system.osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: "87"
    state: present
  notify: Reload OS X Dock

# Enable zoom using scroll
- name: Enable OS X Trackpad tracking speed
  community.general.system.osx_defaults:
    # domain: com.apple.trackpad.scaling
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: float
    value: "3"
    state: present

- name: Enable OS X Trackpad Tap to click
  community.general.system.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: boolean
    value: "1"
    state: present

- name: Enable OS X Mouse Zoom using mouse / trackpad
  community.general.system.osx_defaults:
    domain: com.apple.universalaccess
    key: closeViewScrollWheelToggle
    type: int
    value: "1"
    state: present

- name: Enable OS X Mouse Zoom using Command key
  community.general.system.osx_defaults:
    domain: com.apple.universalaccess
    key: closeViewScrollWheelModifiersInt
    type: int
    value: "1048576"
    state: present

- name: Enable OS X Mouse Zoom Style per screen
  community.general.system.osx_defaults:
    domain: com.apple.universalaccess
    key: closeViewZoomMode
    type: int
    value: "0"
    state: present

- name: Disable MRU (Most recent used spaces)
  community.general.system.osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: "false"
    state: present
  notify: Reload OS X Dock

# Enable 3-finger drag. (Moving with 3 fingers in any window "chrome" moves the window.)
# TODO: This requires reboot to work...
- name: Enable OS X 3 fingers drag (external trackpad)
  community.general.system.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: "1"
    state: present

- name: Enable OS X 3 fingers drag
  community.general.system.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: "1"
    state: present

- name: Enable OS X Two Button mouse
  community.general.system.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    key: MouseButtonMode
    type: string
    value: TwoButton
    state: present

- name: Enable OS X Mouse smart zoom
  community.general.system.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    key: MouseOneFingerDoubleTapGesture
    type: int
    value: "1"
    state: present

- name: Enable OS X Mouse Mission Control
  community.general.system.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    key: MouseTwoFingerDoubleTapGesture
    type: int
    value: "3"
    state: present

- name: Enable OS X Mouse Swipe between pages with one finger and Swipe between full-screen apps with two fingers
  community.general.system.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    key: MouseTwoFingerHorizSwipeGesture
    type: int
    value: "2"
    state: present

- name: Save Screenshots using JPEG
  community.general.system.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: jpg
    state: present
  notify: Reload OS X Dock

- name: Don't show desktop icons
  community.general.system.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: "false"
    state: present
  notify: Reload Finder

- name: Configure Time Machine exclusions
  community.general.system.osx_defaults:
    domain: /Library/Preferences/com.apple.TimeMachine.plist
    key: SkipPaths
    type: array
    value: "{{ timemachine.skip_paths }}"
    state: present
  when:
  - timemachine.skip_paths | length > 0

# vi:ft=ansible
